Project/Project/Models/Instructor.cs
using FiorelloAsp.Models;

namespace Project.Models
{
    public class Instructor : BaseEntity
    {
        public string Fullname { get; set; }
        public string Profession { get; set; }
        public string Image { get; set; }
        public int CourseId { get; set; }
        public Course Course { get; set; }
    }
}

Project/Project/ViewModels/Instructors/InstructorDetailVM.cs
using Project.Models;

namespace Project.ViewModels.Instructors
{
    public class InstructorDetailVM
    {
        public Instructor Instructor { get; set; }
    }
}

Project/Project/ViewModels/Instructors/InstructorVM.cs
using Project.Models;

namespace Project.ViewModels.Instructors
{
    public class InstructorVM
    {
        public IEnumerable<Instructor> Instructors { get; set; }
    }
}

Project/Project/Areas/Admin/Controllers/InstructorController.cs
using Microsoft.AspNetCore.Mvc;
using Project.Services;
using Project.Services.Interfaces;
using Project.ViewModels.Categories;
using Project.ViewModels.Instructors;

namespace Project.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class InstructorController : Controller
    {
        private readonly IInstructorService _instructorService;

        public InstructorController(IInstructorService instructorService)
        {
            _instructorService = instructorService;
        }
        public async Task<IActionResult> Index()
        {
            var instructors = await _instructorService.GetAllAsync();

            InstructorVM response = new InstructorVM()
            {
                Instructors = instructors
            };

            return View(response);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id is null) return BadRequest();

            var instructor = await _instructorService.GetWithCourseAsync((int)id);

            if (instructor is null) return NotFound();

            InstructorDetailVM response = new InstructorDetailVM()
            {
                Instructor = instructor
            };

            return View(response);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id is null) return BadRequest();

            var instructor = await _instructorService.GetByIdAsync((int)id);

            if (instructor is null) return NotFound();

            await _instructorService.DeleteAsync(instructor);

            return RedirectToAction(nameof(Index));
        }
    }
}

Project/Project/Areas/Admin/Views/Instructor/Details.cshtml
@model InstructorDetailVM
@{
    ViewData["Title"] = "Details";
}

<div style="width: 350px;" class="card m-auto d-flex align-items-center justify-content-center">
    <div class="card-body d-grid justify-content-center">
        <h4 class="card-title">Instructor:</h4>
        <div class="d-flex">
            <div class="d-flex align-items-center text-muted font-weight-light">
                <span>@Model.Instructor.Fullname</span>
            </div>
        </div>
        <div class="mt-5 ">
            <div class="image mb-5">
                <img src="~/img/@Model.Instructor.Image" style="width:300px;height:200px; border-radius:50%;" alt="" />
            </div>
            <div class="mb-0 mt-3 flex-grow ">
                <h5 class="me-2 mb-2">Profession:</h5>
                <ul class="list-group list-group-flush">
                        <li class="list-group-item p-0">@Model.Instructor.Profession</li>

                </ul>
            </div>
            <div class="mb-0 mt-3 flex-grow d-flex">
                <h5>Course name: @Model.Instructor.Course.Name</h5>
            </div>
        </div>
    </div>
</div>

Project/Project/Areas/Admin/Views/Instructor/Index.cshtml
@model InstructorVM
@{
    ViewData["Title"] = "Index";
}

<div class="container mt-5">
    <div class="table-responsive">
        <table class="table">
            <h1 class="text-center">
                Instructor
            </h1>
            <div>
                <a class="btn btn-danger btn-sm mt-3 mb-3" asp-area="Admin" asp-controller="Instructor" asp-action="Create">
                    <span>Create instructor</span>
                    <i class="fa-solid fa-plus"></i>
                </a>
            </div>
            @foreach (var item in Model.Instructors)
            {
                <thead>
                    <tr>
                        <th><b>Fullname</b></th>
                        <th><b>Profession</b></th>
                        <th><b>Image</b></th>
                        <th><b>Operations</b></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            @item.Fullname
                        </td>
                        <td>
                            @item.Profession
                        </td>
                        <td>
                            <img style="width: 8rem; height: 8rem;" src="~/img/@item.Image"></img>
                        </td>
                        <td>
                            <a class="btn btn-primary btn-sm" asp-area="Admin" asp-controller="Instructor" asp-action="Details" asp-route-id="@item.Id"><i class="fa-solid fa-info"></i></a>
                            <a class="btn btn-warning btn-sm" asp-action="Edit" asp-route-id="@item.Id"><i class="fa-solid fa-marker"></i></a>
                            <form class="d-inline" method="post" asp-action="Delete" asp-route-id="@item.Id">
                                <button type="submit" class="btn btn-danger btn-sm"><i class="fa-solid fa-trash"></i></button>
                            </form>
                        </td>
                    </tr>
                </tbody>
            }
        </table>
    </div>
</div>