Project/Project/Models/Carousel.cs
using FiorelloAsp.Models;

namespace Project.Models
{
    public class Carousel : BaseEntity
    {
        public string Image { get; set; }
    }
}

Project/Project/ViewModels/Carousels/CarouselCreateVM.cs
using System.ComponentModel.DataAnnotations;

namespace Project.ViewModels.Carousels
{
    public class CarouselCreateVM
    {
        [Required]
        public List<IFormFile> Images { get; set; }
    }
}

Project/Project/ViewModels/Carousels/CarouselEditVM.cs
namespace Project.ViewModels.Carousels
{
    public class CarouselEditVM
    {
        public string Image { get; set; }
        public IFormFile NewImage { get; set; }
    }
}

Project/Project/ViewModels/Carousels/CarouselVM.cs
using Project.Models;

namespace Project.ViewModels.Carousels
{
    public class CarouselVM
    {
        public IEnumerable<Carousel> Carousels { get; set; }
    }
}

Project/Project/Areas/Admin/Controllers/CarouselController.cs
using Educal_MVC.Helpers.Extensions;
using FrontProjectAsp.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Project.Services.Interfaces;
using Project.ViewModels.Carousels;

namespace Project.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CarouselController : Controller
    {
        private readonly ICarouselService _carouselService;
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _environment;


        public CarouselController(ICarouselService carouselService, AppDbContext context, IWebHostEnvironment environment)
        {
            _carouselService = carouselService;
            _context = context;
            _environment = environment;
        }
        public async Task<IActionResult> Index()
        {
            var carousels = await _carouselService.GetAllAsync();

            CarouselVM response = new CarouselVM()
            {
                Carousels = carousels
            };

            return View(response);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CarouselCreateVM request)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            foreach (var item in request.Images)
            {
                if (!item.CheckFileType("image/"))
                {
                    ModelState.AddModelError("Image", "Format is wrong");
                    return View();
                }
                
                if (!item.CheckFileSize(200))
                {
                    ModelState.AddModelError("Image", "Max image size is 200 KB");
                    return View();
                }
            }            

            await _carouselService.CreateAsync(request);

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }

            var carousel = await _context.Carousels.FindAsync((int)id);

            if (carousel == null)
            {
                return NotFound();
            }

            string path = Path.Combine(_environment.WebRootPath, "img", carousel.Image);

            if (System.IO.File.Exists(path))
                System.IO.File.Delete(path);

            _context.Carousels.Remove(carousel);

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }

            var carousel = await _context.Carousels.FindAsync((int)id);

            if (carousel == null)
            {
                return NotFound();
            }

            return View(new CarouselEditVM { Image = carousel.Image });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id, CarouselEditVM request)
        {
            var carousel = await _context.Carousels.FindAsync((int)id);

            if (!request.NewImage.CheckFileType("image/"))
            {
                ModelState.AddModelError("Image", "Format is wrong");
                request.Image = carousel.Image;
                return View(request);
            }
            
            if (!request.NewImage.CheckFileSize(200))
            {
                ModelState.AddModelError("Image", "Max image size is 200 KB");
                request.Image = carousel.Image;
                return View(request);
            }

            if (id == null)
            {
                return BadRequest();
            }

            if (carousel == null)
            {
                return NotFound();
            }

            if (request.NewImage is null) return RedirectToAction(nameof(Index));

            string oldPath = Path.Combine(_environment.WebRootPath, "img", carousel.Image);

            if (System.IO.File.Exists(oldPath))
                System.IO.File.Delete(oldPath);

            string fileName = Guid.NewGuid().ToString() + "-" + request.NewImage.FileName;

            string newPath = Path.Combine(_environment.WebRootPath, "img", fileName);

            await request.NewImage.SaveFileToLocalAsync(newPath);

            carousel.Image = fileName;

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

Project/Project/Areas/Admin/Views/Carousel/Create.cshtml
@model CarouselCreateVM

@{
    ViewData["Title"] = "Create";
}

<div class="container mt-3">
    <h1><b>Create category</b></h1>
    <form class="form-sample mt-5" method="post" asp-action="Create" enctype="multipart/form-data">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label"><b>Category</b></label>
                    <div class="col-sm-9">
                        <input class="form-control" asp-for="Images" maxlength="100" placeholder="Add category..." />
                        <span asp-validation-for="Images" class="text-danger"></span>
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                    <a type="submit" class="btn btn-danger" asp-action="Index">Cancel</a>
                </div>
            </div>
        </div>
    </form>
</div>

Project/Project/Areas/Admin/Views/Carousel/Edit.cshtml
@model CarouselEditVM

@{
    ViewData["Title"] = "Edit";
}

<div class="container mt-3">
    <img src="~/img/@Model.Image" style="height: 12rem; width: 12rem;"></img>
    <h1><b>Edit carousel image</b></h1>
    <form class="form-sample mt-5" method="post" asp-action="Edit" enctype="multipart/form-data">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group row">
                    <label class="col-sm-3 col-form-label"><b>Carousel image</b></label>
                    <div class="col-sm-9">
                        <input class="form-control" asp-for="NewImage" maxlength="100" placeholder="Add category..." />
                        <span asp-validation-for="NewImage" class="text-danger"></span>
                    </div>
                    <button type="submit" class="btn btn-primary mr-2">Submit</button>
                    <a type="submit" class="btn btn-danger" asp-action="Index">Cancel</a>
                </div>
            </div>
        </div>
    </form>
</div>

Project/Project/Areas/Admin/Views/Carousel/Index.cshtml
@model CarouselVM
@{
    ViewData["Title"] = "Index";
}

<div class="container mt-5">
    <div class="table-responsive">
        <table class="table">
            <h1 class="text-center">
                Carousel
            </h1>
            <div>
                <a class="btn btn-danger btn-sm mt-3 mb-3" asp-area="Admin" asp-controller="Carousel" asp-action="Create">
                    <span>Create carousel</span>
                    <i class="fa-solid fa-plus"></i>
                </a>
            </div>
            @foreach (var item in Model.Carousels)
            {
                <thead>
                    <tr>
                        <th><b>Image</b></th>
                        <th><b>Operations</b></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            <img style="width: 8rem; height: 8rem;" src="~/img/@item.Image"></img>
                        </td>
                        <td>
                            <a class="btn btn-warning btn-sm" asp-action="Edit" asp-route-id="@item.Id"><i class="fa-solid fa-marker"></i></a>
                            <form class="d-inline" method="post" asp-action="Delete" asp-route-id="@item.Id">
                                <button type="submit" class="btn btn-danger btn-sm"><i class="fa-solid fa-trash"></i></button>
                            </form>
                        </td>
                    </tr>
                </tbody>
            }
        </table>
    </div>
</div>